Finetune performance
src-d/swivel-spark-prep pull request #8
Opened 2017-06-08 18:14 UTC by bzz

This is new, more performant sharding implementation leveraging order by  `repartitionAndSortWithinPartitions`

2017-06-08 18:15 UTC, bzz commented
Ready to be merged, \cc @smola for review

2017-06-13 07:12 UTC, ajnavarro requested changes

2017-06-13 07:12 UTC, ajnavarro commented on src/main/scala/tech/sourced/swivel/SparkPrepDriver.scala
> +    //Re-implement using fastutils.ObjectIntMap
These comments are TODOs? if yes, add the TODO key.

2017-06-13 07:12 UTC, ajnavarro commented on src/main/scala/tech/sourced/swivel/SparkPrepDriver.scala
> +    //Re-implement using RDD[fastutils.IntArrayList]
These comments are TODOs? if yes, add the TODO key.

2017-06-13 07:12 UTC, ajnavarro commented on src/test/scala/tech/sourced/swivel/medium/CoocsMatrixMediumTest.scala
> +    //assert(coocs.length == expectedCoocs.length)
leftover?

2017-06-14 11:35 UTC, bzz commented
@ajnavarro thank for prompt review! Feedback addressed in dc82e9e

2017-06-14 14:44 UTC, ajnavarro approved these changes

2017-06-14 15:43 UTC, smola approved these changes

2017-06-14 15:43 UTC, merged

2017-06-15 06:51 UTC, bzz commented
@smola @ajnavarro thanks for taking care of it!